SYSTEM:
  GPU_ID : 6,7
  NUM_WORKERS: 4
DATASET:
  TRAIN_DIR : '/data4/mjx/gd/dataset_merge/train'
  VAL_DIR : '/data4/mjx/gd/dataset_merge/val'
  TEST_DIR : '/data4/mjx/gd/dataset_merge/test'
MODEL:
  MODEL_NAME: 'xception'
TRAIN_PARAM:
  IMAGE_SIZE: 214
  TRAIN_BATCH_SIZE : 4
  VAL_BATCH_SIZE: 2
  TEST_BATCH_SIZE : 2
  MOMENTUM : 0.9
  WEIGHT_DECAY: 0.0004
  NUM_EPOCHS : 30
  LR : 0.002
  VAL_INTERVAl : 0
  # 打印间隔STEP
  PRINT_INTERVAL : 100
  # 最低保存模型/计算最优模型epohc阈值
  MIN_SAVE_EPOCH: 1
OUTPUT_DIR:
  SUB_DIR: 'submit_merge/'
  LOG_DIR: 'log_merge/'
  OUT_DIR: '/data4/mjx/gd/output_merge/'